language: go
install: true

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap-dev
  - go get github.com/golang/dep/cmd/dep
  - dep ensure -v
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get github.com/golang/lint/golint                        # Linter
  - go get honnef.co/go/tools/cmd/staticcheck                   # Badass static analyzer/linter
  - go get github.com/fzipp/gocyclo

script:
  - test -z $(gofmt -l $GO_FILES)            # Fail if a .go file hasn't been formatted with gofmt
  - go test -v -race ./...                   # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
  - staticcheck ./...                        # "go vet on steroids" + linter
  - gocyclo -over 19 $GO_FILES               # forbid code with excessively complicated functions
  - golint -set_exit_status $(go list ./...) # one last linter
